name: SAMPLE_DBT_PROJECT
version: 1.0.0
config-version: 2
profile: SAMPLE_DBT_PROJECT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  SAMPLE_DBT_PROJECT:
    +materialized: view
